persons_name = str(input("Input Person Name: ")) #input noun
castles_name = str(input("Input adjective: ")) #adjective
color_for_animal = str(input("Input a color for animal: "))
animal = str(input("Input an animal: "))
place = str(input("Input place: "))
adj1 = str(input("Input adjective: ")) #adjective1
magical_creatures1 = str(input("Input an example of magical creature (in plural form): ")) #plural 
adj2 = str(input("Input adjective: "))
magical_creatures2 = str(input("Input an example of magical creature (in plural form): "))
room = str(input("Input a room(name) in a house: ")) #room
noun1 = str(input("Input noun: ")) #some noun
noun2 = str(input("Input another noun: ")) 
noun3 = str(input("Input noun(in plural form): ")) #plural
dream = str(input("Input adjective: ")) #adjective
noun4 = str(input("Input noun(in plural form): ")) #plural
number = int(input("Input a number: ")) 
measure = str(input("Measure of the time: "))
verb = str(input("Input a verb + ing: ")) #verb + ing
adj_last = str(input("Input adjective: ")) 
noun5 = str(input("Input a noun: "))
print(f"Dear {persons_name},  I am writing to you from a {castles_name} castle in an enchanted forest. I found myself here one day after going for a ride on a {color_for_animal} {animal} in {place}. There are {adj1} {magical_creatures1} and {adj2} {magical_creatures2} here! In the {room} there is a pool full of {noun1}. I fall asleep each night on a {noun2} of {noun3} and dream of {noun4}. It feels as though I have lived here for {number} {measure}. I hope one day you can visit, although the only way to get here now is {verb} on a {adj_last} {noun5}!!")